spring:
  zipkin:
    base-url: http://localhost:9001/
    
  datasource:
    #need to TimeZone settings
    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12opuviv
    #change com.mysql.jdbc.Driver to com.mysql.cj.jdbc.Driver
    #as the first one was deprecated
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update


eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka